### ISSUE TITLE
Thanks for this interface

### ISSUE THREAD

**Issue by RajaSrinivasan** [TamaMcGlinn/ada_raspio#1]
Appreciate your effort in this. I am beginning to experiment.

The type   in Raspbio.GPIO 

type Pin_Type is limited private;

the fact it is limited is causing me a bit of a problem. Reviewing it, I think there is no reason it should be limited. 

private - sure. makes sense.

I am toying with several ways to proceed. What is your analysis?

Regards, Srini

**Comment by TamaMcGlinn** [comment]
Yes, you're right. There's no sense making it limited in this case; you could always create an identical one through the create function anyway, so it's not stopping you from creating overlapping pin mappings.

**Comment by TamaMcGlinn** [comment]
I've removed 'limited'
